language: node_js
node_js:
- '7'
install:
- yarn
- yarn run lint
- npm run build
- cp ./manifest.yml ./dist
cache:
  yarn: true
deploy:
  provider: cloudfoundry
  api: api.run.pivotal.io
  username: david.ahern26@gmail.com
  password:
    secure: kLDS4Q3f7sXM7w6ZarsQ68uEFvb63EhXrLds/D9EHE5jI+vWx5GjbAYz3pIEGNkVHgz/r8d65fpI5UeqMg1uknspJQNT4IQgrOOGwNikF/gaG8LUCHvmnlh2DTm/UIViTd+8FHKir/ikFlss9HZ97SlqrCYFjs+dMrnEtGTUEuY7umIwrJ2Tdav3aE4SFFbaYSwqSfLeHtDtnDhBXqZdWOe897y8k704mobjvQXw6oh3wWHZ2bSAs+n/OwyAH5sLSHpN6TcY7ndXI6oYlm4CVrSxDWp2N+E/hq7s8upgpnqq0Ydm144f+/pyLg4An8JKkKKVhiMbc4LMcbB11Jm4/Br3xE7wbSkAYYVA0gRe+/O5KgHCx71Z2y91kTKaqLY7PEJmmLEUvZYhanuDibezydG9q55pcDUgmglDEHw56exKgkCVYSCnrXB5zun/e7jNSM5gqS0p0bQKy4KjdRvAUkFH297cx4/nmxUvw5Y4OA5BHiJqS6nHZIc0rPg19epwM1ovoS1ECVkScVPr7hyRsULTaCE9DknekDHtI3rBL/SLb3WcK2NWDeZxltVZacnmt+IiEaxzvFTefL/XW17kHqDl83BLvvuaARwKHBmKAX1eBS2Am2vjTZRVkliCI3wZeHXsyDwPcrxOYp0yf3T7b3Um6suNwh5ybEuP1V7DbwE=
  organization: thor
  space: prod
  on:
    branch: master
